services:
  ecommerce:
    image: project
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules